version: 2.1

services: 
   ChallengeChatBot: 
     build: ./ChallengeChatBot.Api/ChallengeChatBot.Api
   depends_on: 
      - "rabbitmq" 
   restart: always 
   
   rabbitmq: # login guest:guest 
     image: rabbitmq:3-management 
     hostname: "localhost" 
     labels: 
       NAME: "rabbitmq" 
     ports: 
     - "4369:4369" 
     - "5671:5671" 
     - "5672:5672" 
     - "25672:25672" 
     - "15671:15671" 
     - "15672:15672"